include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/src/core/l10n/*.dart
    - lib/src/core/l10n/**/*.dart

  errors:
    invalid_annotation_target: ignore
    always_put_required_named_parameters_first: ignore
    lines_longer_than_80_chars: ignore
    flutter_style_todos: ignore
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
