include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    always_put_required_named_parameters_first: ignore
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
